### PR TITLE
dev-java/gradle-bin: 2.14 + 2.14.1

### PR DESCRIPTION
**Pull request by VladRassokhin**
* Add version 2.14

### CODE REVIEW

**Comment by VladRassokhin** [comment]
@chewi Please take a look.
Seems all errors in travis build are unrelated.

**Comment by chewi** [comment]
I'd like @Flowdalic to check it first.

**Comment by Flowdalic** [comment]
utACK

Not sure if one should change the DEPEND of existing ebuilds or if a revision bump is required. But I don't see that as issue since we are not in the main tree.

**Comment by chewi** [comment]
You mean RDEPEND. DEPEND would be okay, RDEPEND is not, but you can probably get away with it in this case. It should be 1.7 though, we don't support 1.6 any more and you shouldn't specify versions you haven't tested.

**Comment by VladRassokhin** [comment]
So, should I remove change in all non 2.14 ebuilds? (drop last commit)

**Comment by chewi** [comment]
Since it's a -bin, it doesn't matter that much so you may as well drop that one.

**Comment by VladRassokhin** [comment]
Removed, only 'add 2.14' left.

**Comment by chewi** [comment]
Merged, sorry it took so long.

**Pull request closed without merging**
